name: CI for ASW2223

on:
  release:
    types: [published]
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
  push:
    branches:    
      - develop
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix restapi install
    - run: npm --prefix webapp run test --coverage --watchAll=false --coverageReporters=lcov
    - run: npm --prefix restapi run test --coverage --watchAll=false --coverageReporters=lcov
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.8
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  e2e-tests:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix restapi install
    - run: npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      env:
        API_URI: http://${{ secrets.DEPLOY_HOST }}:5000/api
      with:
          name: cidinene/asw2223_0/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_URI
  docker-push-restapi:
    name: Push restapi Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
          name: cidinene/asw2223_0/restapi
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: restapi        
  deploy:
    name: gh-pages deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix webapp run prod
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: cidinene/equipoInterfaz5
        publish_branch: gh-pages # default: gh-pages
        publish_dir: ./webapp/build
    
   
