name: CI for ASW2223

on:
  release:
    types: [published]
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
  push:
    branches:    
      - develop
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix restapi install
    - run: npm --prefix webapp run test --coverage --watchAll=false --coverageReporters=lcov
    - run: npm --prefix restapi run test --coverage --watchAll=false --coverageReporters=lcov
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.8
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e-tests:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix restapi install
    - run: npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e    
  deploy:
    needs: [e2e-tests]
    name: gh-pages deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix webapp run build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ASW_DEPLOY }}
        external_repository: cidinene/equipoInterfaz5.github.io
        publish_branch: master # default: gh-pages
        publish_dir: ./webapp/build
        user_name: cidinene
        user_email: cidirene@gmail.com
    
   
